Approval form element [INTEGRALCS-13869]
crusepartnership/formbuilder pull request #23
Opened 2020-05-11 23:32 UTC by lukeluluke

2020-07-01 01:19 UTC, caleobryan requested changes

2020-07-01 01:19 UTC, caleobryan commented on index.html
> +            {id: 11, full_name: 'Cale O\'Bryan', username: 'caleobrian'}
Should I be replaced with a dummy user?

2020-07-01 02:07 UTC, lukeluluke commented on index.html
> +            {id: 11, full_name: 'Cale O\'Bryan', username: 'caleobrian'}
haha, your name helps QA to find a bug, single quote in your name breaks the json.parse function. But I will change as you wish

2020-07-01 21:32 UTC, caleobryan commented on index.html
> +            {id: 11, full_name: 'Cale O\'Bryan', username: 'caleobrian'}
Makes sense, all good :-)

2020-07-01 21:33 UTC, caleobryan approved these changes

2020-07-03 02:47 UTC, chintogtokh approved these changes

2020-07-06 04:17 UTC, merged